[package]
name = "type-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = "0.17.15"
swc_ecma_parser = "0.94.0"
swc_ecma_ast = "0.70.0"
swc_ecma_codegen = "0.95.0"
thiserror = "1.0.30"
log = "0.4.14"
env_logger = "0.9.0"