on:
  push:
    branches:
      - master

jobs:
  build-mac:
    name: Mac executable
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: type-rs-mac
          path: target/release/type-rs

  build-windows:
    name: Windows executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: type-rs-win
          path: target/release/type-rs.exe
  
  build-linux:
    name: Linux executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: type-rs-linux
          path: target/release/type-rs