on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}-clippy
  cancel-in-progress: true

jobs: 
  build-linux:
    name: Linux executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo clippy --all-targets --all-features -- -D warnings