on:
  push:
    branches:
      - master

jobs: 
  build-linux:
    name: Linux executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo clippy